#!/bin/zsh

_gradle 2>/dev/null
functions[_gradle_tasks_all]=${functions[_gradle]}

_gradle_tasks() {
    _selected=()
    _setSelected() {
        _selected=("${words[@]:1}")
    }
    
    _suggestions=()
    _isAnySuggestionSelected() {
        for suggestion in $_suggestions; do
            if [[ " ${_selected[*]} " =~ " ${suggestion} " ]]; then
                return 0
            fi
        done
        return 1
    }
    
    _tasks=(
        "build"
        "clean"
        "test"
    )    
    _isAnyTaskSelected() {
        _suggestions=("${_tasks[@]}")
        _isAnySuggestionSelected
    }
    
    _options=(
      "--parallel"
    )    
    _isAnyOptionSelected() {
        _suggestions=("${_options[@]}")
        _isAnySuggestionSelected
    }
    
    _npmTasks=(
        "npmBuild"
    )
    
    _completions=()
    _withTasksAll() {
        _completions+=("${_tasks[@]}" "${_npmTasks[@]}")
    }
    
    _withTasksRemaining() {
        _setSelected
        tasksRemaining=()
        if _isAnyTaskSelected && ! _isAnyOptionSelected; then
            for task in $_tasks; do
                if [[ ! " ${_selected[*]} " =~ " ${task} " ]]; then
                    tasksRemaining+=("$task")
                fi
            done
        fi
        _completions+=("${tasksRemaining[@]}")
    }
    
    _withOptionsRemaining() {
        _setSelected
        optionsRemaining=()
        for option in $_options; do
            if [[ ! " ${_selected[*]} " =~ " ${option} " ]]; then
                optionsRemaining+=("$option")
            fi
        done
        _completions+=("${optionsRemaining[@]}")
    }
    
    _addCompletions() {
        compadd - $_completions
    }
    
    _tasks() {
        _withTasksAll
        _addCompletions
    }
    
    _remainingTasksAndOptions() {
        _withTasksRemaining
        _withOptionsRemaining
        _addCompletions
    }
    
    _arguments -s \
    '1:_tasks:_tasks' \
    '*:remainingTasks:_remainingTasksAndOptions'
}

# https://github.com/Aloxaf/fzf-tab/issues/65#issuecomment-602144985
_gradle() {
    if [[ -v gradleTasksAll ]]; then
        _gradle_tasks_all
    else
        _gradle_tasks
    fi
}
